### ISSUE TITLE
Removing specific versions from the histroy

### ISSUE THREAD

**Issue by jcsrb** [palkan/logidze#103]
I am currently working on a way to clean up the history as I did not use the `without_logging` wisely in the past in regards to some maintenance tasks and now what to expose part of the history to users.  

My approach is to remove the specific version from the json and updating the number of the other versions.

Is this something that would make sense to added to the gem?
Are there any obvious issues with my approach?

**Comment by palkan** [comment]
> Is this something that would make sense to added to the gem?

Yep, I think that could be useful. Something like `record.remove_log_version(version_number)`.

> Are there any obvious issues with my approach?

Depends on the implementation. I suggest adding a DB-side function/procedure and call it to avoid race conditions, e.g.:

```sql
update my_table set log_data = logidze_remove_version(log_data, version_number) where id = 1
```

**Comment by palkan** [comment]
Closing this for now.
Removing the version from the log is not straightforward as it might seem: we need to care about the log consistency, thus removing a version is closer to compaction, since we need to merge the diff from the removed version with the previous one (or the next one?).

Probably, doing such tasks manually (i.e., in Ruby, smth like `Mode.find_each { |item| LogCleaner.call(item) }`) is a better way.

**Comment by jcsrb** [comment]
here is a helpful snippet,  implementation of `remove_version` works on the json and depends on the exact thing one tries to achieve

```ruby
subject.with_lock do
  raw_history = subject.read_attribute_before_type_cast(:log_data)

  altered_history = remove_version raw_history, version
  Logidze.without_logging do
    subject.update_column(:log_data, altered_history)
  end
end
```
