### ISSUE TITLE
Discussion: Is SQL Format _really_ a requirement?

### ISSUE THREAD

**Issue by colinross** [palkan/logidze#134]
_I understand why, currently, this is a requirement. I'm not questioning current/past limitations, just thinking about future possibilities._

I was looking at the internals of another gem (Scenic) I use (for managing materialized views in particular) and they are able to handle raw SQL-based migration/schema statements without the hard requirement of having to use SQL formatted db/schema.rb

##Digging deeper, and looking at a working example
Scenic seem to have a helper that gets exposed to the AR::Schema `define` block named `create_view` (or `create_materialized_view`) that gets called, passing off the SQL as a HEREDOC block param.
(source code of helpers https://github.com/scenic-views/scenic/blob/b51ed69a223440076a5fa2d48bc5d7764e450eb9/lib/scenic/statements.rb) 

These in turn (scenic has a db-adapter abstraction layer) gets passed of the the adapter, each on having their own special way of handling the actual execution of the statement. e.g. `Scenic.database.create_view(name, sql_definition)`
```
def create_materialized_view(name, sql_definition, no_data: false)
        raise_unless_materialized_views_supported
        execute <<-SQL
  CREATE MATERIALIZED VIEW #{quote_table_name(name)} AS
  #{sql_definition}
  #{'WITH NO DATA' if no_data};
        SQL
      end
```

Obviously there is some filler here that Logidze would not need, but is the general idea one we could use: Supply a help for the schema/migration system to use to create the trigger/s

Is there something else I'm missing? It has been a bit since I really dove deep on logidze's codebase so maybe I'm not seeing another blocker to this general idea.

We would have to have a helper that would essentially take over the job that currently is being done by the generator, but we have that functionality, namely logidze knows the SQL needed for it's triggers given a model name, so theoretically, we should be able to drop the hard requirement of SQL Formatted schema files and instead of running a generator, we'd write a vanilla migration with a helper, such as `logidze_model :post, blacklist: [:created_at, :active], timestamp_column: nil`

Not sure what this looks like for updating the definition, some food for thought.

This all said, I don't think that doing so will directly, dynamically allow anything new or interesting, other than lowering the bar for alternative database support, such as MySQL/Maria, Redshift, etc.

**Comment by palkan** [comment]
Hey @colinross!

That's one of things I wish we had (and is on my "virtual v1.0 roadmap").
Moreover, when I started working on Logidze back in 2016 I had a draft implementation similar to Scenic but due to time constraints had to revert to a simpler approach which we still have today 😞.

So, yes, it's not a requirement, it's a limitation, which could be removed.

> Is there something else I'm missing?

I think, it should be possible to migrate to Scenic-like approach. And there are some blockers, we should get rid of them, too (that's why it's a goal for v1.0, there could be breaking changes).

One workaround that could be probably used today to avoid SQL format is to use fx (https://github.com/teoljungberg/fx) gem. Though that would require some manual work.
