### ISSUE TITLE
Handle schema changes

### ISSUE THREAD

**Issue by palkan** [palkan/logidze#59]
We do not handle such cases, for example, as adding or removing columns. That might lead to undesired behaviour (see #58).

Some thoughts.

When a new column has been added, we might have no initial value for it (i.e. in the first version). Hence for the version prior to adding the column we should (either):
- nullify it
- set to default value (if any)
- raise an error when it's read (thus mimic the old behaviour–undefined column).

Not sure which one is the right way.

**Comment by charlie-wasp** [comment]
For me the third option looks the most reasonable, however it might break some apps, using logidze already.

First two options are less reasonable (imho), because if there wasn’t a column at the certain point in time, so we shouldn’t pretend, that it was :)

Maybe we can implement first and third, and provide a switch between them for users.

What do you think, @palkan?

**Comment by palkan** [comment]
> Maybe we can implement first and third, and provide a switch between them for users.

Yeah, that make sense. And make the third to be a default.

**Comment by palkan** [comment]
Btw, we can use AR missing attribute exception https://github.com/rails/rails/blob/8fd69db783b14dcdde92f4682b8d3c66bdbcb90b/activemodel/lib/active_model/attribute_methods.rb#L470

**Comment by dsalahutdinov** [comment]
Hello @palkan and @charlie-wasp 
Could you please help with this issue sharing your suggestions about way of solving it.

Adding new column (the same case if we change column white list and regenerate triggers) causes starting to track changes of it. 
If I've got right, somewhere [here](https://github.com/palkan/logidze/blob/master/lib/logidze/history.rb#L67) we need to determine that we do not have changes of that column. (but how?) All the knowledge about tracking columns list is in the [sql triggers](https://github.com/palkan/logidze/blob/master/lib/generators/logidze/model/model_generator.rb#L95) so we do not have the way to get it in ruby directly (because it is known only as options when we generate the model table triggers.

One way is to configure tracking columns list in the model class with dsl, and then generate the migration with help of this data, so in this case we will be able to track the case when versions history do not have changes of some column.
